language: php

php:
  - '5.6'
  - '7.0'
  - '7.1'
  - 'nightly'

before_script:
  - pear install pear/PHP_CodeSniffer
  - phpenv rehash
  - nvm install 7.7.1

  

script:
  - vendor/bin/phpunit --coverage-text